import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "./Header";
import Home from "../pages/Home/index";
import Technology from "../pages/technology/technology";
import WhoWeAre from "./WhoWeAre/WhoWeAre";
import WeOffer from "../pages/WeOffer/index";
import Contact from "./Contact-us/Contact";
import Work from "./Work/work";
import Testimonial from "./Testimonial/Testimonial";
import Findus from "./Findus/Findus";
import Footer from "./Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export default function App() {
  return (
    <>
      <Head>
        <title>Zraviya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,500;0,600;1,400&display=swap"
          rel="stylesheet"></link>
      </Head>
      <Header />
      <Home />
      {/* <Technology /> */}
      <WhoWeAre />
      <WeOffer />
      <Contact />
      <Work />
      <Testimonial />
      <Findus />
      <Footer />
    </>
  );
}
